name: Generate Documentation

on:
  push:
    branches:
      - main
    #  - improve-doc

permissions:
  contents: write
  packages: read

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    environment: actions

    container:
      image: ghcr.io/${{ github.repository_owner }}/danda-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.DOCS_PUSH_TOKEN }}

      - name: Debug Git
        run: |
          git remote -v
          git config --list --show-origin

      - name: Mark repository as safe
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          
      - name: build project
        run: |
          pip install -e .[dev]

      - name: Generate documentation
        run: |
          python generate_docs.py

      - name: Commit generated docs
        run: |
          pwd
          git status
          
          git config user.name "mohammad shalabi"
          git config user.email "shalabicloud@gmail.com"

          git add docs/accessor

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "chore: update generated accessor docs"
          git push
