# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: danda tests

on:
  push:
  pull_request:

permissions:
  contents: read
  packages: read

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/${{ github.repository_owner }}/danda-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: Lint
      run: ruff check .

    - name: build project
      run: |
        pip install -e .[dev]

    - name: Test with pytest
      run: |
        pytest
